\c capstone_two_test

DROP TABLE IF EXISTS banks CASCADE;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS users;

CREATE TABLE banks (
  _id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  website TEXT
);

CREATE TABLE cards (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,     
    data json NOT NULL,
    bank_id TEXT REFERENCES banks (_id) ON DELETE CASCADE
);

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text PRIMARY KEY,
        CHECK (position('@' IN email) > 1),
    password text NOT NULL,
    notes text DEFAULT '' NOT NULL,
    join_at timestamp without time zone NOT NULL,
    last_login_at timestamp with time zone,
    is_admin BOOLEAN DEFAULT FALSE,
    api_key text
);


CREATE INDEX data_id_idx ON cards ((data->>'ID'));
CREATE INDEX data_name_idx ON cards ((data->>'Name'));