"""Seed cards data into postgreSQL."""

import psycopg2
import json


conn = psycopg2.connect(host="localhost",
                        database="capstone_two",
                        user=None,
                        password=None,)
curs = conn.cursor()

curs.execute("""
DROP TABLE IF EXISTS cards;
CREATE TABLE cards (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    data jsonb NOT NULL
)
""")

curs.execute("""
CREATE INDEX cards_data_gin_idx ON cards USING GIN(data)
""")


with open("card_data.json", encoding="utf-8") as json_data:
    record_list = json.load(json_data)
    if(type(record_list) == list):
        first_record = record_list[0]
        print(type(first_record))  # <class 'dict'>
        """ Need to convert each python dict to JSON
            -  convert to string
            -  then convert to JSON
        """
        r = json.dumps(first_record)  # convert dict to string
        print(type(r))  # <class 'str'>
        loaded_r = json.loads(r)  # convert string into JSON
        print(type(loaded_r))  # <class 'dict'>
        curs.execute(
            f"INSERT INTO cards (data) VALUES ({loaded_r})")

conn.commit()


# cat card_data2.json | psql -h localhost -p 5432 capstone_two -c "COPY cards (data) FROM STDIN;"
